// <auto-generated />
using System;
using Alias.API.Data.Pii;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Alias.API.Data.Pii.Migrations
{
    [DbContext(typeof(PiiDbContext))]
    partial class PiiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Alias.API.Models.Pii.AliasOwnerMap", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AliasId")
                        .HasColumnType("uuid")
                        .HasColumnName("alias_id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("alias_owner_map_pkey");

                    b.HasIndex(new[] { "AliasId" }, "alias_owner_map_alias_id_key")
                        .IsUnique()
                        .HasDatabaseName("ix_alias_owner_map_alias_id");

                    b.HasIndex(new[] { "UserId" }, "alias_owner_map_user_id_key")
                        .IsUnique()
                        .HasDatabaseName("ix_alias_owner_map_user_id");

                    b.ToTable("alias_owner_map", "pii");
                });
#pragma warning restore 612, 618
        }
    }
}
