// <auto-generated />
using System;
using LifeStyles.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LifeStyles.API.Data.Migrations
{
    [DbContext(typeof(LifeStylesDbContext))]
    [Migration("20250622111955_SplitEmotionFeaturesIntoManyTables")]
    partial class SplitEmotionFeaturesIntoManyTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FoodActivityFoodCategory", b =>
                {
                    b.Property<Guid>("FoodActivitiesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FoodCategoriesId")
                        .HasColumnType("uuid");

                    b.HasKey("FoodActivitiesId", "FoodCategoriesId");

                    b.HasIndex("FoodCategoriesId");

                    b.ToTable("FoodActivityFoodCategory", "public");
                });

            modelBuilder.Entity("FoodActivityFoodNutrient", b =>
                {
                    b.Property<Guid>("FoodActivitiesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FoodNutrientsId")
                        .HasColumnType("uuid");

                    b.HasKey("FoodActivitiesId", "FoodNutrientsId");

                    b.HasIndex("FoodNutrientsId");

                    b.ToTable("FoodActivityFoodNutrient", "public");
                });

            modelBuilder.Entity("LifeStyles.API.Models.Emotion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Emotions", "public");
                });

            modelBuilder.Entity("LifeStyles.API.Models.EmotionSelection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmotionCheckpointId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmotionId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Intensity")
                        .HasColumnType("integer");

                    b.Property<int?>("Rank")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmotionCheckpointId");

                    b.HasIndex("EmotionId");

                    b.ToTable("EmotionSelections", "public");
                });

            modelBuilder.Entity("LifeStyles.API.Models.EntertainmentActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImpactLevel")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("IntensityLevel")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EntertainmentActivities", "public");
                });

            modelBuilder.Entity("LifeStyles.API.Models.FoodActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IntensityLevel")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("MealTime")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FoodActivities", "public");
                });

            modelBuilder.Entity("LifeStyles.API.Models.FoodCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FoodCategories", "public");
                });

            modelBuilder.Entity("LifeStyles.API.Models.FoodNutrient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FoodNutrients", "public");
                });

            modelBuilder.Entity("LifeStyles.API.Models.ImprovementGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ImprovementGoals", "public");
                });

            modelBuilder.Entity("LifeStyles.API.Models.LifestyleLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvailableTimePerDay")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("ExerciseFrequency")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.Property<DateTimeOffset>("LogDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PatientProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("SleepHours")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.HasKey("Id");

                    b.ToTable("LifestyleLogs", "public");
                });

            modelBuilder.Entity("LifeStyles.API.Models.PatientEmotionCheckpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LogDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PatientProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("PatientEmotionCheckpoints", "public");
                });

            modelBuilder.Entity("LifeStyles.API.Models.PatientEntertainmentActivity", b =>
                {
                    b.Property<Guid>("PatientProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EntertainmentActivityId")
                        .HasColumnType("uuid");

                    b.Property<string>("PreferenceLevel")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.HasKey("PatientProfileId", "EntertainmentActivityId");

                    b.ToTable("PatientEntertainmentActivities", "public");
                });

            modelBuilder.Entity("LifeStyles.API.Models.PatientFoodActivity", b =>
                {
                    b.Property<Guid>("PatientProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FoodActivityId")
                        .HasColumnType("uuid");

                    b.Property<string>("PreferenceLevel")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.HasKey("PatientProfileId", "FoodActivityId");

                    b.ToTable("PatientFoodActivities", "public");
                });

            modelBuilder.Entity("LifeStyles.API.Models.PatientImprovementGoal", b =>
                {
                    b.Property<Guid>("PatientProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PatientProfileId", "GoalId");

                    b.HasIndex("GoalId");

                    b.ToTable("PatientImprovementGoals", "public");
                });

            modelBuilder.Entity("LifeStyles.API.Models.PatientPhysicalActivity", b =>
                {
                    b.Property<Guid>("PatientProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PhysicalActivityId")
                        .HasColumnType("uuid");

                    b.Property<string>("PreferenceLevel")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.HasKey("PatientProfileId", "PhysicalActivityId");

                    b.ToTable("PatientPhysicalActivities", "public");
                });

            modelBuilder.Entity("LifeStyles.API.Models.PatientTherapeuticActivity", b =>
                {
                    b.Property<Guid>("PatientProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TherapeuticActivityId")
                        .HasColumnType("uuid");

                    b.Property<string>("PreferenceLevel")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.HasKey("PatientProfileId", "TherapeuticActivityId");

                    b.ToTable("PatientTherapeuticActivities", "public");
                });

            modelBuilder.Entity("LifeStyles.API.Models.PhysicalActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImpactLevel")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("IntensityLevel")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PhysicalActivities", "public");
                });

            modelBuilder.Entity("LifeStyles.API.Models.TherapeuticActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImpactLevel")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IntensityLevel")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TherapeuticTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TherapeuticTypeId");

                    b.ToTable("TherapeuticActivities", "public");
                });

            modelBuilder.Entity("LifeStyles.API.Models.TherapeuticType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TherapeuticTypes", "public");
                });

            modelBuilder.Entity("FoodActivityFoodCategory", b =>
                {
                    b.HasOne("LifeStyles.API.Models.FoodActivity", null)
                        .WithMany()
                        .HasForeignKey("FoodActivitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LifeStyles.API.Models.FoodCategory", null)
                        .WithMany()
                        .HasForeignKey("FoodCategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FoodActivityFoodNutrient", b =>
                {
                    b.HasOne("LifeStyles.API.Models.FoodActivity", null)
                        .WithMany()
                        .HasForeignKey("FoodActivitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LifeStyles.API.Models.FoodNutrient", null)
                        .WithMany()
                        .HasForeignKey("FoodNutrientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LifeStyles.API.Models.EmotionSelection", b =>
                {
                    b.HasOne("LifeStyles.API.Models.PatientEmotionCheckpoint", "EmotionCheckpoint")
                        .WithMany("EmotionSelections")
                        .HasForeignKey("EmotionCheckpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LifeStyles.API.Models.Emotion", "Emotion")
                        .WithMany("EmotionSelections")
                        .HasForeignKey("EmotionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Emotion");

                    b.Navigation("EmotionCheckpoint");
                });

            modelBuilder.Entity("LifeStyles.API.Models.PatientImprovementGoal", b =>
                {
                    b.HasOne("LifeStyles.API.Models.ImprovementGoal", "Goal")
                        .WithMany("PatientImprovementGoals")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("LifeStyles.API.Models.TherapeuticActivity", b =>
                {
                    b.HasOne("LifeStyles.API.Models.TherapeuticType", "TherapeuticType")
                        .WithMany()
                        .HasForeignKey("TherapeuticTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TherapeuticType");
                });

            modelBuilder.Entity("LifeStyles.API.Models.Emotion", b =>
                {
                    b.Navigation("EmotionSelections");
                });

            modelBuilder.Entity("LifeStyles.API.Models.ImprovementGoal", b =>
                {
                    b.Navigation("PatientImprovementGoals");
                });

            modelBuilder.Entity("LifeStyles.API.Models.PatientEmotionCheckpoint", b =>
                {
                    b.Navigation("EmotionSelections");
                });
#pragma warning restore 612, 618
        }
    }
}
