// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using UserMemory.API.Data;

#nullable disable

namespace UserMemory.API.Data.Migrations
{
    [DbContext(typeof(UserMemoryDbContext))]
    partial class UserMemoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MemoryTagUserMemory", b =>
                {
                    b.Property<Guid>("user_memory_id")
                        .HasColumnType("uuid")
                        .HasColumnName("user_memory_id");

                    b.Property<Guid>("memory_tag_id")
                        .HasColumnType("uuid")
                        .HasColumnName("memory_tag_id");

                    b.HasKey("user_memory_id", "memory_tag_id")
                        .HasName("pk_user_memory_tags");

                    b.HasIndex("memory_tag_id")
                        .HasDatabaseName("ix_user_memory_tags_memory_tag_id");

                    b.HasIndex("user_memory_id")
                        .HasDatabaseName("ix_user_memory_tags_user_memory_id");

                    b.ToTable("user_memory_tags", (string)null);
                });

            modelBuilder.Entity("UserMemory.API.Models.AliasDailySummary", b =>
                {
                    b.Property<Guid>("AliasId")
                        .HasColumnType("uuid")
                        .HasColumnName("alias_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<int>("RewardClaimCount")
                        .HasColumnType("integer")
                        .HasColumnName("reward_claim_count");

                    b.HasKey("AliasId", "Date")
                        .HasName("pk_alias_daily_summaries");

                    b.ToTable("alias_daily_summaries", (string)null);
                });

            modelBuilder.Entity("UserMemory.API.Models.MemoryTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_memory_tags");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_memory_tags_code");

                    b.ToTable("memory_tags", (string)null);
                });

            modelBuilder.Entity("UserMemory.API.Models.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("OccurredOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on");

                    b.Property<DateTimeOffset?>("ProcessedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("UserMemory.API.Models.Reward", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AliasId")
                        .HasColumnType("uuid")
                        .HasColumnName("alias_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<JsonDocument>("Meta")
                        .HasColumnType("jsonb")
                        .HasColumnName("meta");

                    b.Property<string>("PromptBase")
                        .HasColumnType("text")
                        .HasColumnName("prompt_base");

                    b.Property<string>("PromptFiller")
                        .HasColumnType("text")
                        .HasColumnName("prompt_filler");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<string>("StickerUrl")
                        .HasColumnType("text")
                        .HasColumnName("sticker_url");

                    b.HasKey("Id")
                        .HasName("pk_rewards");

                    b.ToTable("rewards", (string)null);
                });

            modelBuilder.Entity("UserMemory.API.Models.SessionDailyProgress", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<Guid>("AliasId")
                        .HasColumnType("uuid")
                        .HasColumnName("alias_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<int>("LastIncrement")
                        .HasColumnType("integer")
                        .HasColumnName("last_increment");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<DateOnly>("ProgressDate")
                        .HasColumnType("date")
                        .HasColumnName("progress_date");

                    b.Property<int>("ProgressPoints")
                        .HasColumnType("integer")
                        .HasColumnName("progress_points");

                    b.HasKey("SessionId")
                        .HasName("pk_session_daily_progresses");

                    b.ToTable("session_daily_progresses", (string)null);
                });

            modelBuilder.Entity("UserMemory.API.Models.UserMemory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AliasId")
                        .HasColumnType("uuid")
                        .HasColumnName("alias_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(3072)")
                        .HasColumnName("embedding");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.HasKey("Id")
                        .HasName("pk_user_memories");

                    b.HasIndex("AliasId")
                        .HasDatabaseName("ix_user_memories_alias_id");

                    b.ToTable("user_memories", (string)null);
                });

            modelBuilder.Entity("MemoryTagUserMemory", b =>
                {
                    b.HasOne("UserMemory.API.Models.MemoryTag", null)
                        .WithMany()
                        .HasForeignKey("memory_tag_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_memory_tags_memory_tags_memory_tag_id");

                    b.HasOne("UserMemory.API.Models.UserMemory", null)
                        .WithMany()
                        .HasForeignKey("user_memory_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_memory_tags_user_memories_user_memory_id");
                });
#pragma warning restore 612, 618
        }
    }
}
