// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Promotion.Grpc.Data;

#nullable disable

namespace Promotion.Grpc.Migrations
{
    [DbContext(typeof(PromotionDbContext))]
    [Migration("20250821092033_AdjustDbNamingConventionToSnakeCase")]
    partial class AdjustDbNamingConventionToSnakeCase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Promotion.Grpc.Models.GiftCode", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal>("MoneyValue")
                        .HasColumnType("numeric")
                        .HasColumnName("money_value");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("patient_id");

                    b.Property<string>("PromotionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("promotion_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_gift_codes");

                    b.HasIndex("PromotionId")
                        .HasDatabaseName("ix_gift_codes_promotion_id");

                    b.ToTable("gift_codes", (string)null);
                });

            modelBuilder.Entity("Promotion.Grpc.Models.PromoCode", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PromotionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("promotion_id");

                    b.Property<int>("Value")
                        .HasColumnType("integer")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_promo_codes");

                    b.HasIndex("PromotionId")
                        .HasDatabaseName("ix_promo_codes_promotion_id");

                    b.ToTable("promo_codes", (string)null);
                });

            modelBuilder.Entity("Promotion.Grpc.Models.Promotion", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("EffectiveDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_date");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("ImageId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PromotionTypeId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("promotion_type_id");

                    b.HasKey("Id")
                        .HasName("pk_promotions");

                    b.HasIndex("PromotionTypeId")
                        .HasDatabaseName("ix_promotions_promotion_type_id");

                    b.ToTable("promotions", (string)null);
                });

            modelBuilder.Entity("Promotion.Grpc.Models.PromotionServicePackage", b =>
                {
                    b.Property<string>("PromotionId")
                        .HasColumnType("text")
                        .HasColumnName("promotion_id");

                    b.Property<string>("ServicePackageId")
                        .HasColumnType("text")
                        .HasColumnName("service_package_id");

                    b.HasKey("PromotionId", "ServicePackageId")
                        .HasName("pk_promotion_service_packages");

                    b.ToTable("promotion_service_packages", (string)null);
                });

            modelBuilder.Entity("Promotion.Grpc.Models.PromotionType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_promotion_types");

                    b.ToTable("promotion_types", (string)null);
                });

            modelBuilder.Entity("Promotion.Grpc.Models.PromotionTypeServicePackage", b =>
                {
                    b.Property<string>("PromotionTypeId")
                        .HasColumnType("text")
                        .HasColumnName("promotion_type_id");

                    b.Property<string>("ServicePackageId")
                        .HasColumnType("text")
                        .HasColumnName("service_package_id");

                    b.HasKey("PromotionTypeId", "ServicePackageId")
                        .HasName("pk_promotion_type_service_packages");

                    b.ToTable("promotion_type_service_packages", (string)null);
                });

            modelBuilder.Entity("Promotion.Grpc.Models.GiftCode", b =>
                {
                    b.HasOne("Promotion.Grpc.Models.Promotion", "Promotion")
                        .WithMany("GiftCodes")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gift_codes_promotions_promotion_id");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("Promotion.Grpc.Models.PromoCode", b =>
                {
                    b.HasOne("Promotion.Grpc.Models.Promotion", "Promotion")
                        .WithMany("PromoCodes")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_promo_codes_promotions_promotion_id");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("Promotion.Grpc.Models.Promotion", b =>
                {
                    b.HasOne("Promotion.Grpc.Models.PromotionType", "PromotionType")
                        .WithMany("Promotions")
                        .HasForeignKey("PromotionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_promotions_promotion_types_promotion_type_id");

                    b.Navigation("PromotionType");
                });

            modelBuilder.Entity("Promotion.Grpc.Models.PromotionServicePackage", b =>
                {
                    b.HasOne("Promotion.Grpc.Models.Promotion", "Promotion")
                        .WithMany("PromotionServicePackages")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_promotion_service_packages_promotions_promotion_id");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("Promotion.Grpc.Models.PromotionTypeServicePackage", b =>
                {
                    b.HasOne("Promotion.Grpc.Models.PromotionType", "PromotionType")
                        .WithMany("PromotionTypeServicePackages")
                        .HasForeignKey("PromotionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_promotion_type_service_packages_promotion_types_promotion_t");

                    b.Navigation("PromotionType");
                });

            modelBuilder.Entity("Promotion.Grpc.Models.Promotion", b =>
                {
                    b.Navigation("GiftCodes");

                    b.Navigation("PromoCodes");

                    b.Navigation("PromotionServicePackages");
                });

            modelBuilder.Entity("Promotion.Grpc.Models.PromotionType", b =>
                {
                    b.Navigation("PromotionTypeServicePackages");

                    b.Navigation("Promotions");
                });
#pragma warning restore 612, 618
        }
    }
}
